### ISSUE TITLE
Spotify Viewer Not Showing Track Info

### ISSUE THREAD

**Issue by streamyay** [MarcoPNS/Spotify-Stream-Widget#11]
My viewer, while spotify is playing, is only showing <<Track Name>> <<Artist Name>> instead of the info from spotify. Album artwork is not showing and the progress slider is not populated.

**Comment by MarcoPNS** [comment]
Problem is solved. Update to version 1.2.1.5 and everything is fine 😄

**Comment by streamyay** [comment]
Awesome is there a link to download the update? I'm not seeing how to in the app itself.

**Comment by MarcoPNS** [comment]
When you open the Spotify Stream Widget a update notification should pop up: 
![image](https://user-images.githubusercontent.com/35105681/42906175-a0260c6a-8ada-11e8-823f-2fc4b28fcfac.png)
When you press "yes" then you will be redirected to the release page
![image](https://user-images.githubusercontent.com/35105681/42906198-b43ac6b4-8ada-11e8-9138-286904e5c560.png)

You can find the newest version here: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases

**Comment by MarcoPNS** [comment]
Unfortunately I need to reopen the issue again. It seems so that Spotify killed the local API. Yesterday they only changed it a bit but now it is completely blocked. I will write to you when I have more infos

**Comment by MarcoPNS** [comment]
@Alpha018 yes! 

> Remote control of Spotify’s desktop app has been deprecated in favour of full track playback in the browser. 
[https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/](https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/)

So they are two options now:
 1. I can try to use the Web API which means that the user need a internet connection, third party tracks will not be recognized and the user will need to authentificat the application to get access to his current track infos.
 2. Try to get the infos from the System Media Transport Controls (I will now call it SMTC) which means that I could get all the necessary playback data from any audio player which also use the SMTC. The problem is that the SMTC is not made for getting data. You can only send data to it. Maybe I will find a solution for it.

_Meanwhile, I'm improving the readability of the code so others can understand it better and maybe can help me with that problem. That would be great!_

**Comment by MarcoPNS** [comment]
Status Update: no chance to get my hands to the System Media Transport Controls. Also it works only on Windows 10. Current Plan: I will now switch to the Spotify Web API and I want to add more "Providers" like iTunes or Google Play! I guess I could publish an update in a week. Stay tuned!

**Comment by Zwornn** [comment]
Hello !

I found your widget This morning, and i saw it wasn't working anymore on spotify desktop cause they removed the web running option and i just found this post. You said you could publish an update in a week and i wanted to know i you know the release date?

I can't wait haha. This is the only one spotify widget and you did it great.
I hope you did it :)

**Comment by PMRBrab** [comment]
+1 , other solutions either look bad or you have to do million things to get it going

**Comment by MarcoPNS** [comment]
@Zwornn @PMRBrab Unfortunately, I have not worked on it yet. But I work on it today and I will stream on Twitch. https://www.twitch.tv/marcnado

**Comment by PMRBrab** [comment]
@MarcoPNS Did you make some progress during your session or by end of last week? 👍

**Comment by Zwornn** [comment]
Seems not x)
Maybe he's busy

**Comment by PMRBrab** [comment]
:-[

**Comment by MarcoPNS** [comment]
Update: sorry but I don’t have the time atm. If someone want to edit the code then feel free to do it and make a pull request. Thanks!

**Comment by Alpha018** [comment]
is it possible to use NodeJS to make the same action?

**Comment by MarcoPNS** [comment]
@Alpha018 Sure but that would be a complete new project since I use .NET Framework for this application.

**Comment by MarcoPNS** [comment]
Just took a year lol

I worked on the tool again this weekend. The move to the Web API only costed me one day. Here is it. 

### [Spotify Stream Widget v1.3.0.0](https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.3.0.0)

Issue fixed and closed.
