### ISSUE TITLE
Does not update with Streamlabs Chatbot song request

### ISSUE THREAD

**Issue by PixelFilter** [MarcoPNS/Spotify-Stream-Widget#6]
When I use Streamlabs Chatbot, the artwork and song name does not change. Only the status bar changes. It basically defaults to the first song's artwork for the entire playlist.

**Comment by MarcoPNS** [comment]
Which version do you use? Does this only happen when the song get changed by a "third party"

**Comment by PixelFilter** [comment]
I'm on 1.2.0.0. And yes if a third party changes the spotify track, the widget doesn't update it's artwork or name. But the bar keeps playing.

**Comment by MarcoPNS** [comment]
Alright! It seem so that the "TrackChangeEventArgs" don't happen in this moment which is the only event that update the artwork and the name. Interesting.... I would like to know how exactly Streamlabs call the Spotify API. Unfortunately the Chatbot is not Open Source. I'm not sure if I am able to fix this but I will try my best.

**Comment by PixelFilter** [comment]
I think you can look into the source of Nightbot. Nightbot also provides the ability to control Spotify. Nightbot and Chatbot might have some similarities with regard to Spotify integration.

**Comment by MarcoPNS** [comment]
Just published a new version. Please test it if this still happen: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.2.0.7

Feel free to reopen the issue if the issue still appears

**Comment by PixelFilter** [comment]
Hey @MarcoPNS ,

The issue still persists. Apologies for the delayed response.

**Comment by MarcoPNS** [comment]
#8
