### ISSUE TITLE
Troubles with Desktop version

### ISSUE THREAD

**Issue by AlexeyevLL** [MarcoPNS/Spotify-Stream-Widget#71]
Used widget for a while and everything was ok. Don't know what happen, but now widget catch  Spotify only in browser and totally ignore desktop version.
Windows 10. Widget 1.5.0.0

**Comment by MarcoPNS** [comment]
Hello! Thanks for the info, unfortunately I do not quite understand the problem. What exactly is not working?

**Comment by AlexeyevLL** [comment]
Widget cath track info from browser and doesn't from desktop

**Comment by BrigadeMindless** [comment]
I am a web streamer having the same exact issue.  Presented with the previous version after using it almost daily with no issues.  Upgraded to 1.5 and the issue is persisting.

Shows connected to Spotify, but the track/title window does not propagate.    I have tested this with both the Windows 10 App as well as a Chrome browser window.

I am based in the United States.
[2022-09-21.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9619688/2022-09-21.log)
[2022-09-14.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9619694/2022-09-14.log)
[2022-09-21.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9619695/2022-09-21.log)

**Comment by AlexeyevLL** [comment]
> Hi! Thanks for the screenshot, are you from Russia by any chance? Currently no Spotify API access is allowed from Russia.

I am from Kazakhstan. The same?

**Comment by MarcoPNS** [comment]
As there are two versions of the desktop app - one from the spotify website and one from the Microsoft app store, could you try to [install](https://support.spotify.com/article/reinstall-spotify/) the one you do not currently have to see if that would make any difference.
